name: Deploy Easy Oficina (HML)

on:
   push:
      branches: [homol]
jobs:
   deploy-app:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout Code
           uses: actions/checkout@v4

         - name: Setup PHP
           uses: shivammathur/setup-php@v2
           with:
              php-version: '8.5'
              extensions: mbstring, xml, pdo_pgsql, pgsql, bcmath
              coverage: none

         - name: Instalar Dependencias PHP
           run: composer install --no-dev --optimize-autoloader --no-progress

         - name: Setup NodeJS
           uses: actions/setup-node@v4
           with:
              node-version: '20'

         - name: Complilar Assets (Vite + Vue + Inertia)
           run: |
               npm install
               npm run build

         - name: Criar arquivo .env a partir da Secret
           run: |
              echo "${{ secrets.HOMOL_ENV_FILE }}" > .env

         - name: Preparar permissões (Pré-Deploy)
           uses: appleboy/ssh-action@master
           with:
              host: ${{ secrets.HOMOL_SERVER_HOST }}
              username: ${{ secrets.HOMOL_SERVER_USER }}
              key: ${{ secrets.HOMOL_SERVER_KEY }}
              script: |
                sudo chown -R ubuntu:ubuntu /var/www/app

                # Remove manualmente as pastas que costumam travar o rsync
                rm -rf /var/www/app/storage/app/.gitignore
                rm -rf /var/www/app/storage/framework/cache/data/*

         - name: Sincronizar Arquivos no Servidor
           run: |
                 echo "${{ secrets.HOMOL_SERVER_KEY }}" > private_key
                 chmod 600 private_key

                 rsync -rlzt -O --delete --no-perms --no-owner --no-group \
                      -e "ssh -i private_key -o StrictHostKeyChecking=no" \
                      --exclude=".git/" \
                      --exclude=".github/" \
                      --exclude="node_modules/" \
                      --exclude="vendor/" \
                      --exclude="storage/" \
                      --exclude="bootstrap/cache/" \
                      ./ ${{ secrets.HOMOL_SERVER_USER }}@${{ secrets.HOMOL_SERVER_HOST }}:/var/www/app

                 rm private_key

         - name: Comandos Pós Deploy
           uses: appleboy/ssh-action@master
           with:
             host: ${{ secrets.HOMOL_SERVER_HOST }}
             username: ${{ secrets.HOMOL_SERVER_USER }}
             key: ${{ secrets.HOMOL_SERVER_KEY }}
             script: |
               cd /var/www/app
               echo "${{ secrets.ENV_FILE }}" | tr -d '\r' > .env

               mkdir -p storage/framework/{sessions,views,cache/data}
               sudo chown -R www-data:www-data /var/www/app/storage /var/www/app/bootstrap/cache
               sudo chmod -R 775 /var/www/app/storage /var/www/app/bootstrap/cache

               php artisan app:migrate-tenants
               php artisan config:clear
